export const demoRecords = [
  {
    id: 1,
    recordNo: "CERT001",
    text: "This certificate is awarded to John Doe for successfully completing the Advanced Web Development Course with excellence. The course covered React.js, Node.js, and Modern Web Development practices over a period of 6 months.",
    certificateImage: "https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 2,
    recordNo: "CERT002",
    text: "In recognition of outstanding achievement, this certificate is presented to Sarah Smith for mastering the Data Science Fundamentals Program. The program included Machine Learning, Statistical Analysis, and Python Programming.",
    certificateImage: "https://images.unsplash.com/photo-1532619675605-1ede6c2ed2b0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 3,
    recordNo: "CERT003",
    text: "Certificate of Excellence awarded to Michael Johnson for completing the Cloud Architecture Certification with distinction. This comprehensive program covered AWS, Azure, and Cloud Security principles.",
    certificateImage: "https://images.unsplash.com/photo-1517842645767-c639042777db?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
  }
];

const records = [
  {
    type: "Single",
    date: "2024-03-05",
    description: "Sample Description 5",
    recordName: "Record 5",
    country: "Australia",
    state: "Sydney",
    recordNumber: "98127654",
    name: "Charlie Davis",
    certificateId: "AUS-SYD-10001",
    achievement: "Fastest 100m sprint in sand (9.85 seconds)",
    recipient: "Charlie Davis",
    eventDetails: 'Achieved at "Sydney Sports Arena" during the Annual Sports Championship on March 5, 2024.',
    category: "Speed",
    verificationStatus: "Verified",
    issuedBy: "The Book of World Record Committee",
    issuedDate: "2024-06-25",
    witnesses: ["Michael Johnson", "Sarah Lewis"],
    organization: "Sydney Sports Association",
    location: {
      venue: "Sydney Sports Arena",
      city: "Sydney",
      country: "Australia",
    },
  },
  {
    type: "Team",
    date: "2024-05-10",
    description: "Longest domino chain made of books",
    recordName: "Domino Book Chain",
    country: "USA",
    state: "California",
    recordNumber: "12547896",
    name: "Emily Carter",
    certificateId: "USA-CA-90002",
    achievement: "Longest domino chain made of books (2,500 books)",
    recipient: "Emily Carter",
    eventDetails: 'Achieved at "Los Angeles Central Library" in collaboration with "National Library Week 2024".',
    category: "Creativity",
    verificationStatus: "Verified",
    issuedBy: "The Book of World Record Committee",
    issuedDate: "2024-07-01",
    witnesses: ["Dr. Alex Warner", "Julia Roberts"],
    organization: "National Library Association",
    location: {
      venue: "Los Angeles Central Library",
      city: "Los Angeles",
      country: "USA",
    },
  },
  {
    type: "Single",
    date: "2023-12-18",
    description: "Longest time holding a yoga plank",
    recordName: "Endurance Challenge",
    country: "India",
    state: "Maharashtra",
    recordNumber: "56321478",
    name: "Rajesh Khanna",
    certificateId: "IND-MH-30009",
    achievement: "Longest time holding a yoga plank (8 hours 15 minutes)",
    recipient: "Rajesh Khanna",
    eventDetails: 'Achieved at "Mumbai Fitness Expo 2023", certified by the Indian Yoga Federation.',
    category: "Endurance",
    verificationStatus: "Verified",
    issuedBy: "The Book of World Record Committee",
    issuedDate: "2023-12-20",
    witnesses: ["Suresh Patil", "Neha Sharma"],
    organization: "Indian Yoga Federation",
    location: {
      venue: "Mumbai Fitness Expo",
      city: "Mumbai",
      country: "India",
    },
  },
  {
    type: "Single",
    date: "2024-06-21",
    description: "Longest time breath held voluntarily",
    recordName: "Deep Dive Challenge",
    country: "USA",
    state: "New York",
    recordNumber: "90027",
    name: "Jane Writer",
    certificateId: "USA-NYC-90027",
    achievement: "Longest time breath held voluntarily (18 minutes 05.47 seconds - female)",
    recipient: "Jane Writer",
    eventDetails: 'Achieved at an event organized by "The Book of World Record" at Rockland County, New Square, New York, held by "IYA".',
    category: "Endurance",
    verificationStatus: "Verified",
    issuedBy: "The Book of World Record Committee",
    issuedDate: "2024-06-21",
    witnesses: ["Dr. John Smith", "Emily Thompson"],
    organization: "IYA",
    location: {
      venue: "Rockland County, New Square",
      city: "New York",
      country: "USA",
    },
  },
];

export default records;

